# Generated by Django 6.0.2 on 2026-02-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kitob nomi')),
                ('author', models.CharField(max_length=200, verbose_name='Muallif')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='Muqova rasmi')),
                ('pdf_file', models.FileField(blank=True, upload_to='books/', verbose_name='PDF fayl')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='Sahifalar soni')),
                ('language', models.CharField(default="O'zbek", max_length=50, verbose_name='Til')),
                ('published_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nashr yili')),
                ('available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-created_at'],
            },
        ),
    ]
