# Generated by Django 6.0.2 on 2026-03-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student profile', 'verbose_name_plural': 'Student profiles'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='direction',
            field=models.CharField(max_length=200, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.CharField(max_length=100, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number'),
        ),
    ]
