# Generated by Django 6.0.2 on 2026-03-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='photo_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Photo image'),
        ),
    ]
